name: Scala Build

on:
  workflow_call:
    inputs:
      target-os:
        description: "List of operating systems to build on."
        default: "ubuntu-latest"
        required: false
        type: string
      java-versions:
        description: "List of Java versions to target."
        default: "8"
        required: false
        type: string
      preserve-cache-between-runs:
        description: "Preserve project cache between new runs."
        default: false
        required: false
        type: boolean

jobs:
  build:
    name: Scala Build
    strategy:
      matrix:
        os: ${{fromJson(inputs.target-os)}}
        java: ${{fromJson(inputs.java-versions)}}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Need full history to update last modified time.
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java }}
        cache: sbt
    - uses: sbt/setup-sbt@v1
      with:
        sbt-runner-version: 1.9.9
    - name: Clean, delete step later
      run: sbt +clean
    - name: Compile and Test
      run: sbt checkPR
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-reports
        path: |
          **/target/test-reports/*.xml
          !target/**
        overwrite: true
    - name: Aggregate Coverage Reports
      run: sbt coverageAggregate
    - name: Code Coverage Report Markdown
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: target/scala-2.13/coverage-report/cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
    - uses: jwalton/gh-find-current-pr@v1
      id: finder
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        path: code-coverage-results.md
        number: ${{ steps.finder.outputs.pr }}
